### ISSUE TITLE
Google Calendar integration

### ISSUE THREAD

**Issue by simon-weber** [alexkay/muspy#11]
For about a year I've had a little script that pulls down my muspy releases and puts them into a "releases" Google Calendar. I think it's kind of elegant: it fixes the issue of getting releases only around the time of release (#9), and gives you more options in how you want to be notified.

Here's the script I've been using: https://gist.github.com/simon-weber/4968381.

If this is compelling to anyone else, I can look into integrating into muspy (if @alexkay wants the feature).
![release_cal](https://f.cloud.github.com/assets/950506/164042/8ebd9b5a-7870-11e2-884b-e3816e7d5d45.png)

**Comment by alexkay** [comment]
@simon-weber Looks great, would be nice to have this integrated.

**Comment by simon-weber** [comment]
Cool; I'd love to implement it.

When I've got a chance I'll put up some ideas here - I'm new to django, so you'll probably want to sanity-check my plans =)

**Comment by simon-weber** [comment]
Ok, so I've actually got time to do this now. Stuff I think would need to be done:
- model additions
  - user's OAuth credentials
  - user's chosen google calendar id/whether they're using the feature
- frontend
  - add to muspy.com/settings: OAuth flow, choice of calendar, removal of this stuff
- daemon
  - create calendar events

To be able to update release events on the calendar after creation (like when the date changes), you'd also have to store gcal ids, too.

**Comment by simon-weber** [comment]
Oh, hey, forget all of that; it'd be _way_ easier to just export an ical in the same way you currently export an rss feed (thanks, @clehner!).

What do you think about that?

**Comment by simon-weber** [comment]
closed by #19
