### ISSUE TITLE
Nothing for months, then bombarded with emails

### ISSUE THREAD

**Issue by DoctorSugarbear** [alexkay/muspy#16]
I signed up months ago and kinda forgot about it. After a few months went buy I suddenly got a bunch of emails about "new" releases (obviously they were all pretty old at this point.)

**Comment by alexkay** [comment]
How many artists do you follow and how many notifications have you received?

I don't see any spikes in the aggregate number of emails sent out, you probably just got unlucky with MusicBrainz edits for the particular artists that you follow.

Closing, but feel free to re-open if this happens again.
