### ISSUE TITLE
Feature Request - Sort Artists

### ISSUE THREAD

**Issue by almeidaxan** [alexkay/muspy#17]
Hello Alex,

First of all, thank you for your time on this great (and free) music notifier service. It's great and very reliable!

As for the feature request, it would be nice having an option to sort my added artists by name (in https://muspy.com/artists), so I can easily check if I already added one specific artist or not, since I'm not very good memorizing.

Thank you, and I'll be looking for more,
Alexandre

**Comment by alexkay** [comment]
Glad to hear you like the service :)

As for the feature request, could you elaborate a bit? The list is already sorted by the normalized artist name (e.g. with "The" stripped and the family name put in front).

**Comment by almeidaxan** [comment]
As by sort, I meant sort alphabetically. All artists are showing up in a random name order, then it looks somewhat unsortted. I might be missing some settings or something, though...
—
Alexandre E. Almeida
(19) 8172-1055

**Comment by almeidaxan** [comment]
Ohhhhh my bad! Now I see what's up!
You can mark the request as done, if you want to.
—
Alexandre E. Almeida
(19) 8172-1055
