### ISSUE TITLE
No Listing for "Muse"

### ISSUE THREAD

**Issue by alecjcook** [alexkay/muspy#20]
I found on the music brainz website a listing for the UK Rockband "Muse" but on your site, nothing... Any idea why?

http://musicbrainz.org/artist/9c9f1380-2516-4fc9-a3e6-f9f61941d090

**Comment by alexkay** [comment]
Artists get added to muspy when someone starts to follows them for the first time. It looks like this has already happened to Muse: https://muspy.com/artist/9c9f1380-2516-4fc9-a3e6-f9f61941d090

**Comment by alecjcook** [comment]
OK cool! must have been a bit of a delay. I feel privileged to be the first
Muse Follower. I'm expecting great things out of this app! Many thanks!!! :)

**Comment by alecjcook** [comment]
please close this buG!!
