### ISSUE TITLE
Criteria for an album to be "released"?

### ISSUE THREAD

**Issue by Scalie** [alexkay/muspy#24]
More than 24 hours ago I added a couple of albums to MusicBrainz: http://musicbrainz.org/release/4319cbcb-c048-46b2-a798-a1975210971c and http://musicbrainz.org/release/e32a61a5-dade-418f-8e16-d7e7de0de874 in order to assert that the service works as intended, but they don't appear in the artists' releases. Are albums missing certain data overlooked?

**Comment by Scalie** [comment]
The albums were recognized as released, one of them yesterday and the other one today. It seems that it just takes more than one day for them to be processed.

**Comment by alexkay** [comment]
@Mircoder It indeed takes up to 48 hours to sync with Musicbrainz.
