### ISSUE TITLE
Importing

### ISSUE THREAD

**Issue by Robotejin** [alexkay/muspy#29]
Issue
"Importing
These artists will be imported shortly:"

Hi. Lately I've tried to add all the artists in my library, just to give you an idea that would be around 400 artists. The situation is that the message above has been there for the last three days, and none of the artists is being imported.
Did I do something wrong? Am I not supposed to have these many artists added on Muspy?

I've tried sending an email to info@muspy.com but had no response... 

Please help.
- Leo

**Comment by ghost** [comment]
Same here. I started importing less than 400 artists. It's been like this for two days. Nothing so far...

**Comment by alexkay** [comment]
There was a bug in background job processing which is fixed now. It should process all pending imports in the next few hours. I'll close this issue when it's all done.
