### ISSUE TITLE
Invalid code, you password was not reset.

### ISSUE THREAD

**Issue by kadem2** [alexkay/muspy#34]
Why is this happening? I never changed my password and suddenly I can't login, but when I go to reset it, the reset link gives me this error. Help?

**Comment by hashhar** [comment]
Same issue here. Although my feed links are working correctly I cannot log in to my user.

**Comment by dirkdiggla69** [comment]
Same problem here.  Please Help!

**Comment by chal8** [comment]
same here!

**Comment by alexkay** [comment]
Sorry for delay, I was afk for a week.

The muspy database got corrupted, I had to restore it from a one week old backup. Please let me know if anything is still not functional.
