### ISSUE TITLE
can't import artists anymore, and the updates on email has stopped

### ISSUE THREAD

**Issue by chal8** [alexkay/muspy#36]
whenever I try to add more artists from my last.fm profile I get this message "You already have a pending import. Please wait until the import finishes before importing again. Refresh this page to track the progress." But it's been like that for weeks!

Also, the last email update on new releases I received was at the end of april.

**Comment by alok** [comment]
I've noticed this too

**Comment by makalawliet** [comment]
I also have a problem with this

**Comment by alexkay** [comment]
Should be fixed, thank you for reporting!
