### ISSUE TITLE
A couple of feature requests

### ISSUE THREAD

**Issue by stasleo** [alexkay/muspy#4]
Thank you for amazing service!
I think the following features can be implemented:
1) permanent linking to last.fm profile in settings
2) service suggestion about adding new artist to following list, e.g. it will analyze most listened artist during last month, and if these artists are not in the following list - send notification to email about adding artists
3) black list - do not suggest artists, that user has already declined to folllow
4) login using lastfm and facebook accounts.
5) more modern and good-looking site design
6) Android and iOS application

**Comment by stasleo** [comment]
7) Also when I imported artists from lastfm, they instantly added to following list. It is not very good, because my list consists of 100+ artists and it is a pain in ass to look through the whole list and delete those I don't want to follow. I think it should be added to pending temporal list, and only after approval should go to following list.

**Comment by umrysh** [comment]
In regards to #6 on the list I have personally been using a Muspy Android app for some time. It's on the Google Play store as [Muspy for Android](https://play.google.com/store/apps/details?id=com.danielme.muspyforandroid). Hope this helps.

**Comment by alexkay** [comment]
@stasleo, I'm going to close this issue and open one per each request.
1. #6
2. I want to keep muspy a simple tool which does only one thing. There are plenty of music recommendation services (though none of them are doing a good job for me, which is telling)
3. Declined how? Could you describe a scenario?
4. #7
5. I'm not a designer, pull requests are welcome.
6. As @umrysh  mentioned, someone wrote an Android app which uses the muspy API. Feel free to do the same for iOS.
7. #8

**Comment by stasleo** [comment]
Part 3: When user uncheck some band - it should be added to a special black list, it means that user doesn't want this band to follow. When he imports bands again - they should be skipped (currently bands added again to list, and user HAVE TO uncheck bands again. I think it's unfriendly behavior). 
Additional `black list` page is also expected, if this part 3 will be implemented. I think users should have possibility to remove bands from black list.
