### ISSUE TITLE
Option to select which type of releases to be notified about / follow

### ISSUE THREAD

**Issue by hashhar** [alexkay/muspy#40]
I would like to add an option so that each user can chose to selectively follow "Albums", "Singles" and "EPs". This information can be extracted from the title of the release using simple pattern matching.

If you can tell me a little about how the code is structured and whether you are willing to merge this feature, I can code it up and submit a PR.

**Comment by alexkay** [comment]
@hashhar: There's already an option to get notified about certain album types.
