### ISSUE TITLE
"You already have a pending import"

### ISSUE THREAD

**Issue by MikeMilligan** [alexkay/muspy#49]
Hello.

Since the past few days I cannot import new artists to my profile and this is the message I get:

_You already have a pending import. Please wait until the import finishes before importing again. Refresh this page to track the progress._

It has been like that for a week or so.

Thanks in advance.

**Comment by alexkay** [comment]
Thank you for flagging @MikeMilligan! I fixed the underlying issue, the backlog should finish processing in a day or two.
