### ISSUE TITLE
The certificate of muspy.com has expired

### ISSUE THREAD

**Issue by d4k0** [alexkay/muspy#50]
Hi,

It seems that the certificate of muspy.com has expired. I now always get a SEC_ERROR_EXPIRED_CERTIFICATE error in Firefox and Thunderbird also complains about the certificate. Chrome based browsers show a similar message. Could you please renew the certificate?

**Comment by alexkay** [comment]
Fixed, thank you for the heads up!

**Comment by d4k0** [comment]
@alexkay It seems that the certificate expired again today.

**Comment by ghost** [comment]
I guess the Let's encrypt autorenewal script is not working for any reason. Maybe the server is using an old version of certbot.

**Comment by alexkay** [comment]
Fixed, apologies for that. For some reason the cron job renewing the certificate is not doing its job, I'll investigate later.
