### ISSUE TITLE
The certificate of muspy.com has expired 

### ISSUE THREAD

**Issue by ghost** [alexkay/muspy#53]
The certificate expired yesterday.

Thanks in advance.

https://github.com/alexkay/muspy/issues/50

**Comment by d4k0** [comment]
@alexkay 

It seems the cron job renewing the certificate is still not working :-/.

**Comment by alexkay** [comment]
Thank you for reporting (again :sweat:) and sorry it took a week to fix, I was travelling without a terminal.

The crontab was misconfigured which broke automated renewals. Fixed and double checked renewals from cron work.

**Comment by ghost** [comment]
Thanks!!!
