### ISSUE TITLE
Some artists not updating?

### ISSUE THREAD

**Issue by JohnChristmann** [alexkay/muspy#67]
For instance, Ad Infinitum: [https://musicbrainz.org/artist/f9cfdf4e-a437-42f0-a9ff-f6a598fa803d](https://musicbrainz.org/artist/f9cfdf4e-a437-42f0-a9ff-f6a598fa803d) shows 3 singles and 1 album more recent than Muspy does over the past year and a half or so: [https://muspy.com/artist/f9cfdf4e-a437-42f0-a9ff-f6a598fa803d](https://muspy.com/artist/f9cfdf4e-a437-42f0-a9ff-f6a598fa803d)

I checked and these releases are properly listed in Musicbrainz API searches.

**Comment by alexkay** [comment]
I think I identified and fixed the issue. Give it a week or two to catch up. Thank you for reporting!

**Comment by JohnChristmann** [comment]
Thanks for investigating!  I'll report back if it still seems to be missing releases in a couple weeks.

**Comment by JohnChristmann** [comment]
Alright Ad Infinitum finally updated today and quite a few other artists on my follow list got updated over the past couple weeks so short of verifying every single one of them manually I'm going to call it fixed.
